version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: keepassxc
    path: ./.github/config/keepassxc.dict
    addWords: true
dictionaries:
  - keepassxc
words: []
ignoreWords: []
import: []
